name: Angular - Tests
on:
  push:
    branches: ['develop', 'release-*']
jobs:
  build-angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: {fetch-depth: 0}
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run-script build-prod  # package.json -> "scripts"
    # - run: npm run-script test  # "ng test --no-watch --no-progress --browsers=ChromeHeadlessCI"
      - name: Slack WebHook
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,author,commit,author,workflow,
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: SonarCloud Scan
        if: success()
        uses: SonarSource/sonarcloud-github-action@master # file: sonar-project.properties
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
