name: CI
on:
  push:
    branches:
      - develop
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Install dependencies
        run: npm ci
      - name: Build Angular App
        run: npm run-script build-prod  # package.json -> "scripts"
      - name: Tests
        run: npm run-script test-ci  # package.json -> "scripts"
      - name: Slack WebHook
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,author,commit,author,workflow,
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: SonarCloud Scan
        if: success()
        uses: SonarSource/sonarcloud-github-action@v2 # file: sonar-project.properties
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
